include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.4.4/templates/scala.yml'

test sbt-datadog:
  extends: .sbt-test
  tags: []

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []

